#!/usr/bin/env python3
"""Generate the Cyrillic Reference pan-Cyrillic character table.

Reads the aggregated character set from the Paratype Cyrillic language
knowledge base (a sibling `cyrillic-languages/` repository) and writes a
master table of every single Cyrillic character used across the 77
languages in scope, with its Unicode codepoint and descriptive name.

Downstream stages add:
  * decomposition of composed characters ("… WITH MACRON", "… WITH
    DIAERESIS AND BREVE", …) into base + combining-mark sequences,
  * Private Use Area (PUA) → standard-sequence mapping with a legacy
    PUA column for backwards compatibility,
  * SVG illustrations of each letter via the glyphplotter tool.

Usage:
    python3 generate.py
    python3 generate.py --data ../cyrillic-languages --out .

Python 3.8+ stdlib only.
"""

import argparse
import json
import re
import sys
import unicodedata
from pathlib import Path


PUA_RANGE = (0xE000, 0xF8FF)
PUA_TOKEN = re.compile(r"^!([0-9A-Fa-f]{4,5})$")

# Sentinel for the Cyrillic-specific breve — resolved per case in decompose().
# The generic combining breve U+0306 is NOT used here: Paratype Expert fonts
# carry a distinct Cyrillic breve at U+F6D1 (uppercase) and U+F6D4 (lowercase)
# that is the shape typographers expect on top of a Cyrillic base.
_CYRILLIC_BREVE = object()
CYRILLIC_BREVE_UC = 0xF6D1
CYRILLIC_BREVE_LC = 0xF6D4

ACCENT_COMBINING_MARK = {
    "MACRON":       0x0304,
    "DIAERESIS":    0x0308,
    "BREVE":        _CYRILLIC_BREVE,
    "ACUTE":        0x0301,
    "CIRCUMFLEX":   0x0302,
    "GRAVE":        0x0300,
    "CARON":        0x030C,
    "DOUBLE ACUTE": 0x030B,
    "CEDILLA":      0x0327,
    "DOT ABOVE":    0x0307,
}

_WITH_RE = re.compile(r"\s+WITH\s+", re.IGNORECASE)
_AND_RE = re.compile(r"\s+AND\s+", re.IGNORECASE)

# The 77 Cyrillic-based languages this project covers. Values match JSON
# file stems under `<data>/library/cyrillic/base/`.
LANGUAGES_IN_SCOPE = [
    "Abazin", "Abkhazian", "Adyge", "Aghul", "Altaic (Oirot)", "Avar",
    "Azeri", "Bashkir", "Belarusian", "Bulgarian", "Buryat", "Chechen",
    "Chukchi", "Chuvash", "Dargwa", "Dolgan", "Dungan", "Enets",
    "Eskimo (Yupik)", "Even (Lamut)", "Evenki (Tungus)", "Gagauz",
    "Ingush", "Itelmen", "Kabardian", "Kabardino-Cirkassian", "Kalmyk",
    "Karachay-Balkar", "Karakalpak", "Kazakh", "Khakass", "Khanty",
    "Kirghiz", "Komi-Permyak", "Komi-Zyrian", "Koryak", "Kryashen Tatar",
    "Kumyk", "Kurdish", "Lak", "Lezgin", "Macedonian", "Manci",
    "Mari-high", "Mari-low", "Moldavian", "Mongolian", "Mordvin-Erzya",
    "Mordvin-Moksha", "Nanai", "Negidal", "Nenets (Yurak)", "Nganasan",
    "Nivkh", "Nogai", "Ossetic", "Russian", "Rutul", "Saami Kildin",
    "Selkup", "Serbian", "Shor", "Tabasaran", "Tadzhik", "Talysh", "Tat",
    "Tatar", "Tofalar", "Touva (Soyot)", "Tsakhur", "Turkmen", "Udmurt",
    "Uighur", "Ukrainian", "Ulch", "Yakut", "Yukagir",
]


def resolve_data_root(data_arg: Path) -> Path:
    """Return the directory that directly contains `library/cyrillic/base/`.

    Accepts either the data subfolder or the cloned-repo root that holds it
    one level down — so the tool works whether run from a sibling clone or
    from inside the combined source tree during development.
    """
    if (data_arg / "library" / "cyrillic" / "base").is_dir():
        return data_arg
    nested = data_arg / "cyrillic-languages"
    if (nested / "library" / "cyrillic" / "base").is_dir():
        return nested
    raise FileNotFoundError(
        f"Could not find library/cyrillic/base/ under {data_arg} "
        f"or {nested}. Pass --data pointing at the cloned "
        f"cyrillic-languages repository."
    )


def load_pan_cyrillic(data_root: Path) -> dict:
    """Load the aggregated pan-Cyrillic character set.

    The pan-Cyrillic JSON is generated by the source repository's pipeline
    from every enabled language file. Its `uppercase_unicodes_list` and
    `lowercase_unicodes_list` contain one entry per unique character with
    its codepoint(s), description, and the languages that use it.
    """
    path = data_root / "site" / "cyrillic" / "cyrillic_characters_lib.json"
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def is_pua(codepoint: int) -> bool:
    return PUA_RANGE[0] <= codepoint <= PUA_RANGE[1]


def format_unicodes(unicodes: list[str]) -> str:
    """Format a list of hex strings as `XXXX + XXXX + …`."""
    return " + ".join(u.upper() for u in unicodes)


def _diagram_cell(family: str, subdir: str, cp_hex: str, img_width: int) -> str:
    """<img>+txt cell pointing at svg/<family>/<subdir>/<cp>.{svg,txt}."""
    return (
        f'<img src="svg/{family}/{subdir}/{cp_hex}.svg" width="{img_width}" '
        f'alt="{family} U+{cp_hex}"> [txt](svg/{family}/{subdir}/{cp_hex}.txt)'
    )


def has_decomposition_hint(description: str) -> bool:
    """Return True for descriptions like '… WITH MACRON' / '… WITH DIAERESIS AND BREVE'.

    Covers both decomposable and structural composites (e.g. `… WITH HOOK`);
    `decompose()` is the actual gate that separates the two.
    """
    return " with " in f" {description.lower()} "


_KNOWN_COMBINING_MARK_CPS = {
    0x0304, 0x0308, 0x0306, 0x0301, 0x0302,
    0x0300, 0x030C, 0x030B, 0x0327, 0x0307,
}


def _swap_breve(cp: int, case: str) -> int:
    """Generic combining breve U+0306 → Cyrillic case-specific breve."""
    if cp == 0x0306:
        if case == "upper":
            return CYRILLIC_BREVE_UC
        if case == "lower":
            return CYRILLIC_BREVE_LC
        raise ValueError(f"_swap_breve: unknown case {case!r}")
    return cp


def decompose(description: str, case: str, sign: str = "") -> list[int] | None:
    """Break a composed Cyrillic codepoint into base + combining marks.

    Tries two paths in order:

    1. **Description-based.** If the Unicode description contains
       `... WITH <accent>[ AND <accent>]`, parse out the base letter
       name and the accent tokens. Works for every Paratype composite
       that spells out its accents (e.g. Ӑ, F50E).
    2. **NFD fallback.** If the description has no `WITH` but the
       character itself has a canonical Unicode decomposition into a
       base plus combining marks from our known set (all of U+0300…
       U+030C), use that. This picks up the common precomposed letters
       whose Unicode names only carry a language name (Ё, Й, Ў, Ѓ, Ї, Ќ
       and their lowercase forms) — roughly 12 additional rows.

    Returns a list of codepoints (base first) or None if neither path
    applies (structural composites like `WITH DESCENDER`, plain letters
    without a composition, etc.).

    `case` must be `"upper"` or `"lower"` — selects U+F6D1 or U+F6D4
    for the BREVE token wherever it appears (Paratype Expert's Cyrillic-
    shaped breve, not the generic combining U+0306).
    """
    # Path 1: ... WITH <accent>
    parts = _WITH_RE.split(description, maxsplit=1)
    if len(parts) == 2:
        base_name, phrase = parts
        tokens = [t.strip().upper() for t in _AND_RE.split(phrase)]
        mapped: list[int] = []
        for token in tokens:
            mark = ACCENT_COMBINING_MARK.get(token)
            if mark is None:
                return None
            if mark is _CYRILLIC_BREVE:
                mapped.append(_swap_breve(0x0306, case))
            else:
                mapped.append(mark)
        try:
            base_char = unicodedata.lookup(base_name.strip().upper())
        except KeyError:
            raise ValueError(
                f"decompose: cannot resolve base letter {base_name!r} "
                f"from description {description!r}"
            )
        return [ord(base_char), *mapped]

    # Path 2: NFD fallback for precomposed characters whose description
    # does not spell out the accent.
    if sign:
        nfd = unicodedata.normalize("NFD", sign)
        if len(nfd) > 1:
            cps = [ord(c) for c in nfd]
            if all(cp in _KNOWN_COMBINING_MARK_CPS for cp in cps[1:]):
                return [cps[0], *(_swap_breve(cp, case) for cp in cps[1:])]

    return None


def dedupe_by_codepoints(entries: list[dict]) -> list[dict]:
    """Merge entries that share the same codepoint sequence.

    The pan-Cyrillic set intentionally emits duplicate rows for localized
    forms (`&` marker → `local='bg'` etc.) and style variants — these share
    a Unicode codepoint but render differently via an OpenType `locl` or
    stylistic feature. For the master character table we keep one row per
    codepoint sequence, union the language lists, and record which locales
    request a localized form in a `locales` field.
    """
    by_key: dict[tuple[str, ...], dict] = {}
    for entry in entries:
        key = tuple(u.upper() for u in entry.get("unicodes", []))
        if key not in by_key:
            merged = dict(entry)
            merged["unicodes"] = list(key)
            merged["languages"] = list(entry.get("languages", []))
            merged["locales"] = {entry.get("local")} if entry.get("local") else set()
            by_key[key] = merged
        else:
            merged = by_key[key]
            merged["languages"].extend(entry.get("languages", []))
            if entry.get("local"):
                merged["locales"].add(entry.get("local"))
    for merged in by_key.values():
        merged["locales"] = sorted(merged["locales"])
    return list(by_key.values())


def classify_variant_token(token: str) -> dict | None:
    """Decode a source token that carries a variant marker.

    Returns a dict with keys `marker` (`localized` / `alternate`), `style`
    (`any` / `straight` / `italic`), `glyph_text` (the text after markers
    are stripped, e.g. `г`), and `codepoints` (list of uppercase hex
    strings). Returns None for plain tokens with no marker — those belong
    in the main character table, not in the variants table.
    """
    if not token:
        return None
    rest = token
    if rest[0] == "&":
        marker = "localized"
        rest = rest[1:]
    elif rest[0] == "+":
        marker = "alternate"
        rest = rest[1:]
    else:
        return None
    style = "any"
    for suffix, label in ((".ita", "italic"), (".str", "straight"), (".alt", "alt")):
        if rest.endswith(suffix):
            style = label
            rest = rest[: -len(suffix)]
            break
    if not rest:
        return None
    pua_match = PUA_TOKEN.match(rest)
    if pua_match:
        codepoints = [f"{int(pua_match.group(1), 16):04X}"]
    else:
        codepoints = [f"{ord(c):04X}" for c in rest]
    return {
        "marker": marker,
        "style": style,
        "glyph_text": rest,
        "codepoints": codepoints,
    }


_FONT_GAPS_SUPPRESSED = {
    # Variants whose `.<SUFFIX>` glyph is not present in PT Serif Expert
    # Regular and so cannot be rendered. Suppressed from the table to avoid
    # broken-image rows; tracked in TODO.md for the type-design team.
    ("0416", "bg"),  # Ж — no uni0416.BGR
    ("041A", "bg"),  # К — no uni041A.BGR
}


def collect_glyph_variants(data_root: Path, languages: list[str]) -> list[dict]:
    """Scan in-scope base JSONs and collect every token with a variant marker.

    One entry per (codepoints, case, locale, style, marker, language) tuple.
    Later aggregation merges rows that share everything except `language`.

    Filters out variants that fall in `_FONT_GAPS_SUPPRESSED` — those rows
    are real per the source data but cannot be rendered until the font's
    glyph set is extended.
    """
    variants: list[dict] = []
    base_dir = data_root / "library" / "cyrillic" / "base"
    for lang_name in languages:
        path = base_dir / f"{lang_name}.json"
        if not path.exists():
            continue
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        locale = data.get("local", "")
        for block in data.get("glyphs_list", []):
            block_type = block.get("type", "")
            for side in ("uppercase", "lowercase"):
                for token in (block.get(side, "") or "").split():
                    info = classify_variant_token(token)
                    if info is None:
                        continue
                    # `alternate` rows describe the default (pre-locl) shape
                    # that pairs with each `&`-marker row. The paired
                    # localized row's Diagram cell already renders both
                    # shapes side-by-side (default → variant), so the alt
                    # row carries no information the reader doesn't already
                    # see. Drop it. (Side effect: the old ru-default filter
                    # is subsumed — ru sources only ever emit `+` tokens,
                    # never `&`, so they disappear from the table either
                    # way.)
                    if info["marker"] == "alternate":
                        continue
                    # Suppress font-gap rows (variant glyph missing from the
                    # font).
                    if info.get("codepoints") and (info["codepoints"][0], locale) in _FONT_GAPS_SUPPRESSED:
                        continue
                    variants.append({
                        **info,
                        "token": token,
                        "case": side,
                        "locale": locale,
                        "language": lang_name,
                        "block_type": block_type,
                    })
    return variants


def aggregate_variants(variants: list[dict]) -> list[dict]:
    """Merge variant rows that share (codepoints, case, locale, style, marker).

    Different languages sometimes encode the same localized/alternate form;
    those get folded into a single row with a merged `languages` list.
    """
    groups: dict[tuple, dict] = {}
    for v in variants:
        key = (
            tuple(v["codepoints"]), v["case"], v["locale"],
            v["style"], v["marker"],
        )
        if key not in groups:
            groups[key] = {
                "codepoints": v["codepoints"],
                "case": v["case"],
                "locale": v["locale"],
                "style": v["style"],
                "marker": v["marker"],
                "glyph_text": v["glyph_text"],
                "tokens": {v["token"]},
                "languages": {v["language"]},
            }
        else:
            groups[key]["tokens"].add(v["token"])
            groups[key]["languages"].add(v["language"])
    rows = []
    for g in groups.values():
        rows.append({
            **g,
            "tokens": sorted(g["tokens"]),
            "languages": sorted(g["languages"]),
        })
    rows.sort(key=lambda r: (
        [int(cp, 16) for cp in r["codepoints"]],
        r["case"],
        r["locale"],
        r["style"],
        r["marker"],
    ))
    return rows


def render_glyph_variants_md(rows: list[dict]) -> str:
    """Render the variants table — locl (`&`) shape variants only.

    `+`-marker rows were dropped during collection: they described the
    default (pre-locl) shape that each `&` row swaps out, but the
    paired localized row's Diagram cell already renders both shapes
    side-by-side, so the alternate row was redundant information.
    """
    by_style = {"any": 0, "straight": 0, "italic": 0, "alt": 0}
    for r in rows:
        by_style[r["style"]] = by_style.get(r["style"], 0) + 1
    locales = sorted({r["locale"] for r in rows if r["locale"]})

    out: list[str] = []
    out.append("# Glyph variants")
    out.append("")
    out.append(
        "Glyphs that do **not** have their own Unicode codepoint: they "
        "share a codepoint with a base letter, but render as a different "
        "shape under an OpenType `locl` feature (a localized form "
        "selected by the active language), sometimes with a style "
        "qualifier tying the swap to upright (`.str`) or italic (`.ita`) "
        "shaping."
    )
    out.append("")
    out.append(
        "This table complements the pan-Cyrillic character tables in "
        "`characters-uppercase.md` / `characters-lowercase.md`, which are "
        "deduplicated by codepoint. The entries below are the "
        "variant-form rows that the codepoint-level view collapses."
    )
    out.append("")
    out.append(
        f"**{len(rows)}** locl variants — "
        f"styles: any={by_style['any']}, "
        f"straight={by_style.get('straight', 0)}, "
        f"italic={by_style.get('italic', 0)}. "
        f"Locales represented: {', '.join(locales) if locales else '—'}."
    )
    out.append("")
    out.append("## Columns")
    out.append("")
    out.append(
        "- **Codepoint** — the Unicode codepoint the variant swaps shape for "
        "(same as the base letter in the main table), except for the Bashkir "
        "and Chuvash PUA-locl rows where it is the target PUA codepoint."
    )
    out.append(
        "- **Case** — uppercase / lowercase."
    )
    out.append(
        "- **Locale** — `bg` Bulgarian, `sr` Serbian, `ba` Bashkir, or "
        "`cv` Chuvash. These are the four non-default (non-ru) locl tags "
        "for which PT Serif Expert carries named variant glyphs."
    )
    out.append(
        "- **Style** — `straight` or `italic` when the source token has "
        "a `.str` / `.ita` suffix; `any` otherwise."
    )
    out.append(
        "- **Diagram** — an inline SVG showing `default shape → variant "
        "shape` plus a `[txt]` link to the glyphplotter source."
    )
    out.append(
        "- **Languages** — language files that declare this variant."
    )
    out.append("")
    out.append("## Variants")
    out.append("")
    out.append("| # | Codepoint | Case | Locale | Style | Sans | Serif | Languages |")
    out.append("| ---: | --- | --- | --- | --- | :---: | :---: | --- |")
    for i, r in enumerate(rows, start=1):
        # Variant diagrams are always 2 boxes (default → variant), viewBox
        # width 4040 → rendered width 170 at height ~100.
        sans_cell = serif_cell = ""
        if r["locale"] and r["codepoints"]:
            cp_hex = r["codepoints"][0].upper()
            stem = f"{cp_hex}.{r['locale']}"
            sans_cell = (
                f'<img src="svg/Sans/variants/{stem}.svg" width="170" '
                f'alt="Sans U+{cp_hex} .{r["locale"]}"> '
                f"[txt](svg/Sans/variants/{stem}.txt)"
            )
            serif_cell = (
                f'<img src="svg/Serif/variants/{stem}.svg" width="170" '
                f'alt="Serif U+{cp_hex} .{r["locale"]}"> '
                f"[txt](svg/Serif/variants/{stem}.txt)"
            )
        out.append(
            f"| {i} | {format_unicodes(r['codepoints'])} | {r['case']} | "
            f"{r['locale']} | {r['style']} | {sans_cell} | {serif_cell} | "
            f"{', '.join(r['languages'])} |"
        )
    out.append("")
    return "\n".join(out)


def render_characters_md(side: str, entries: list[dict]) -> str:
    """Render the master table for either uppercase or lowercase characters."""
    case = "upper" if side == "uppercase" else "lower"

    pua_count = sum(
        1 for e in entries
        for u in e.get("unicodes", [])
        if is_pua(int(u, 16))
    )
    with_count = 0          # rows whose description contains WITH
    nfd_only_count = 0      # rows decomposed only via the NFD fallback path
    decomposed_count = 0    # rows with any decomposition
    row_cells: list[str] = []
    for entry in entries:
        description = entry.get("description", "")
        sign = entry.get("sign", "")
        unicodes = entry.get("unicodes", [])
        has_with = has_decomposition_hint(description)
        if has_with:
            with_count += 1
        seq = decompose(description, case, sign=sign)
        if seq is not None:
            decomposed_count += 1
            decomp_cell = " + ".join(f"{cp:04X}" for cp in seq)
            if not has_with:
                nfd_only_count += 1
            # Cross-validate the WITH-path result against NFD for non-PUA rows:
            # our decomposition must match NFD except that BREVE uses F6D1/F6D4
            # where NFD would use U+0306. Mismatch = accent table / base-letter
            # lookup is wrong. (The NFD-fallback path is NFD-derived by
            # construction, so no need to cross-check it.)
            is_pua_row = any(is_pua(int(u, 16)) for u in unicodes)
            if has_with and not is_pua_row and sign:
                nfd = unicodedata.normalize("NFD", sign)
                if len(nfd) > 1:
                    nfd_cps = [ord(c) for c in nfd]
                    expected = [
                        (CYRILLIC_BREVE_UC if case == "upper" else CYRILLIC_BREVE_LC)
                        if cp == 0x0306 else cp
                        for cp in nfd_cps
                    ]
                    if seq != expected:
                        raise AssertionError(
                            f"decompose mismatch for {sign!r} "
                            f"({description!r}): got {seq}, expected {expected}"
                        )
        else:
            decomp_cell = ""
        row_cells.append(decomp_cell)
    descriptive_count = with_count - (decomposed_count - nfd_only_count)

    out: list[str] = []
    out.append(f"# Pan-Cyrillic single characters — {side}")
    out.append("")
    out.append(
        f"**{len(entries)}** unique {side} characters across the 77 "
        f"languages in scope. Of these, **{pua_count}** are encoded in "
        f"the Unicode Private Use Area (E000–F8FF). "
        f"**{decomposed_count}** decompose into a base character plus "
        f"one or more combining marks — {decomposed_count - nfd_only_count} "
        f"via a `… WITH …` description and {nfd_only_count} via canonical "
        f"Unicode NFD on precomposed letters whose name carries only the "
        f"language label (Ё, Й, Ў, …). **{descriptive_count}** are "
        f"structural modifications (Descender, Hook, Tail, Stroke, Bar, "
        f"Tick, Upturn, Middle Hook, Vertical Stroke, or the Stroke+Hook "
        f"pair) with no standard combining-mark equivalent — kept as "
        f"their codepoint plus the descriptive name."
    )
    out.append("")
    out.append(
        "Decomposition note: the `BREVE` combining mark in Cyrillic rows "
        "resolves to `U+F6D1` (uppercase) / `U+F6D4` (lowercase) — the "
        "Cyrillic-shaped breve glyphs carried by Paratype Expert fonts — "
        "rather than the generic combining breve `U+0306`, whose shape "
        "does not match Cyrillic typography."
    )
    out.append("")
    out.append(
        "Codepoints are shown in uppercase hex. Multi-codepoint sequences "
        "use `XXXX + XXXX + …` in reading order (base first)."
    )
    out.append("")
    out.append("| # | Sign | Codepoint | Description | PUA | Decomposition | Sans | Serif | Locales |")
    out.append("| ---: | :---: | --- | --- | :---: | --- | :---: | :---: | --- |")
    subdir = "uc" if side == "uppercase" else "lc"
    for i, (entry, decomp_cell) in enumerate(zip(entries, row_cells), start=1):
        sign = entry.get("sign", "")
        unicodes = entry.get("unicodes", [])
        description = entry.get("description", "")
        pua_flag = "yes" if any(is_pua(int(u, 16)) for u in unicodes) else ""
        locales = ", ".join(entry.get("locales", []))
        # Sans / Serif diagram cells: embed the generated SVG inline with
        # an explicit width (target rendered height ~100px) and a link to
        # the glyphplotter source. Widths come from the deterministic
        # viewBox per diagram type: 1440 (single), 6640 (1 accent),
        # 9240 (2 accents).
        cp_hex = unicodes[0].upper() if unicodes else ""
        if cp_hex:
            n_accents = decomp_cell.count("+") if decomp_cell else 0
            svg_width = 1440 if n_accents == 0 else (2600 * n_accents + 4040)
            img_width = round(svg_width * 100 / 2380)
            sans_cell = _diagram_cell("Sans", subdir, cp_hex, img_width)
            serif_cell = _diagram_cell("Serif", subdir, cp_hex, img_width)
        else:
            sans_cell = serif_cell = ""
        out.append(
            f"| {i} | {sign} | {format_unicodes(unicodes)} | "
            f"{description} | {pua_flag} | {decomp_cell} | "
            f"{sans_cell} | {serif_cell} | {locales} |"
        )
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--data", type=Path, default=Path("../cyrillic-languages"),
        help="Path to the sibling cyrillic-languages repository "
             "(default: ../cyrillic-languages)",
    )
    parser.add_argument(
        "--out", type=Path, default=Path("."),
        help="Output directory (default: current directory)",
    )
    args = parser.parse_args(argv)

    if not args.data.exists():
        parser.error(f"--data directory does not exist: {args.data}")

    try:
        data_root = resolve_data_root(args.data)
    except FileNotFoundError as exc:
        parser.error(str(exc))

    pan = load_pan_cyrillic(data_root)
    args.out.mkdir(parents=True, exist_ok=True)

    # Read the codepoint-sorted view rather than the Paratype sort order so
    # PUA entries naturally group at the end of each table.
    upper = dedupe_by_codepoints(pan.get("uppercase_sorted_by_unicodes", []))
    lower = dedupe_by_codepoints(pan.get("lowercase_sorted_by_unicodes", []))

    (args.out / "characters-uppercase.md").write_text(
        render_characters_md("uppercase", upper), encoding="utf-8"
    )
    (args.out / "characters-lowercase.md").write_text(
        render_characters_md("lowercase", lower), encoding="utf-8"
    )

    variants = aggregate_variants(collect_glyph_variants(data_root, LANGUAGES_IN_SCOPE))
    (args.out / "glyph-variants.md").write_text(
        render_glyph_variants_md(variants), encoding="utf-8"
    )

    print(f"Wrote {args.out}/characters-uppercase.md ({len(upper)} entries)")
    print(f"Wrote {args.out}/characters-lowercase.md ({len(lower)} entries)")
    print(f"Wrote {args.out}/glyph-variants.md ({len(variants)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
