#!/usr/bin/env python3
"""Generate the Cyrillic Reference pan-Cyrillic character table.

Reads the aggregated character set from the Paratype Cyrillic language
knowledge base (a sibling `cyrillic-languages/` repository) and writes a
master table of every single Cyrillic character used across the 77
languages in scope, with its Unicode codepoint and descriptive name.

Downstream stages add:
  * decomposition of composed characters ("… WITH MACRON", "… WITH
    DIAERESIS AND BREVE", …) into base + combining-mark sequences,
  * Private Use Area (PUA) → standard-sequence mapping with a legacy
    PUA column for backwards compatibility,
  * SVG illustrations of each letter via the glyphplotter tool.

Usage:
    python3 generate.py
    python3 generate.py --data ../cyrillic-languages --out .

Python 3.8+ stdlib only.
"""

import argparse
import json
import re
import sys
from pathlib import Path


PUA_RANGE = (0xE000, 0xF8FF)
PUA_TOKEN = re.compile(r"^!([0-9A-Fa-f]{4,5})$")

# The 77 Cyrillic-based languages this project covers. Values match JSON
# file stems under `<data>/library/cyrillic/base/`.
LANGUAGES_IN_SCOPE = [
    "Abazin", "Abkhazian", "Adyge", "Aghul", "Altaic (Oirot)", "Avar",
    "Azeri", "Bashkir", "Belarusian", "Bulgarian", "Buryat", "Chechen",
    "Chukchi", "Chuvash", "Dargwa", "Dolgan", "Dungan", "Enets",
    "Eskimo (Yupik)", "Even (Lamut)", "Evenki (Tungus)", "Gagauz",
    "Ingush", "Itelmen", "Kabardian", "Kabardino-Cirkassian", "Kalmyk",
    "Karachay-Balkar", "Karakalpak", "Kazakh", "Khakass", "Khanty",
    "Kirghiz", "Komi-Permyak", "Komi-Zyrian", "Koryak", "Kryashen Tatar",
    "Kumyk", "Kurdish", "Lak", "Lezgin", "Macedonian", "Manci",
    "Mari-high", "Mari-low", "Moldavian", "Mongolian", "Mordvin-Erzya",
    "Mordvin-Moksha", "Nanai", "Negidal", "Nenets (Yurak)", "Nganasan",
    "Nivkh", "Nogai", "Ossetic", "Russian", "Rutul", "Saami Kildin",
    "Selkup", "Serbian", "Shor", "Tabasaran", "Tadzhik", "Talysh", "Tat",
    "Tatar", "Tofalar", "Touva (Soyot)", "Tsakhur", "Turkmen", "Udmurt",
    "Uighur", "Ukrainian", "Ulch", "Yakut", "Yukagir",
]


def resolve_data_root(data_arg: Path) -> Path:
    """Return the directory that directly contains `library/cyrillic/base/`.

    Accepts either the data subfolder or the cloned-repo root that holds it
    one level down — so the tool works whether run from a sibling clone or
    from inside the combined source tree during development.
    """
    if (data_arg / "library" / "cyrillic" / "base").is_dir():
        return data_arg
    nested = data_arg / "cyrillic-languages"
    if (nested / "library" / "cyrillic" / "base").is_dir():
        return nested
    raise FileNotFoundError(
        f"Could not find library/cyrillic/base/ under {data_arg} "
        f"or {nested}. Pass --data pointing at the cloned "
        f"cyrillic-languages repository."
    )


def load_pan_cyrillic(data_root: Path) -> dict:
    """Load the aggregated pan-Cyrillic character set.

    The pan-Cyrillic JSON is generated by the source repository's pipeline
    from every enabled language file. Its `uppercase_unicodes_list` and
    `lowercase_unicodes_list` contain one entry per unique character with
    its codepoint(s), description, and the languages that use it.
    """
    path = data_root / "site" / "cyrillic" / "cyrillic_characters_lib.json"
    with path.open(encoding="utf-8") as f:
        return json.load(f)


def is_pua(codepoint: int) -> bool:
    return PUA_RANGE[0] <= codepoint <= PUA_RANGE[1]


def format_unicodes(unicodes: list[str]) -> str:
    """Format a list of hex strings as `XXXX + XXXX + …`."""
    return " + ".join(u.upper() for u in unicodes)


def has_decomposition_hint(description: str) -> bool:
    """Return True for descriptions like '… WITH MACRON' / '… WITH DIAERESIS AND BREVE'.

    These are the entries that will need a base + combining-mark sequence
    in the next pipeline stage (§4.1 / §4.9 of the spec).
    """
    return " with " in f" {description.lower()} "


def dedupe_by_codepoints(entries: list[dict]) -> list[dict]:
    """Merge entries that share the same codepoint sequence.

    The pan-Cyrillic set intentionally emits duplicate rows for localized
    forms (`&` marker → `local='bg'` etc.) and style variants — these share
    a Unicode codepoint but render differently via an OpenType `locl` or
    stylistic feature. For the master character table we keep one row per
    codepoint sequence, union the language lists, and record which locales
    request a localized form in a `locales` field.
    """
    by_key: dict[tuple[str, ...], dict] = {}
    for entry in entries:
        key = tuple(u.upper() for u in entry.get("unicodes", []))
        if key not in by_key:
            merged = dict(entry)
            merged["unicodes"] = list(key)
            merged["languages"] = list(entry.get("languages", []))
            merged["locales"] = {entry.get("local")} if entry.get("local") else set()
            by_key[key] = merged
        else:
            merged = by_key[key]
            merged["languages"].extend(entry.get("languages", []))
            if entry.get("local"):
                merged["locales"].add(entry.get("local"))
    for merged in by_key.values():
        merged["locales"] = sorted(merged["locales"])
    return list(by_key.values())


def classify_variant_token(token: str) -> dict | None:
    """Decode a source token that carries a variant marker.

    Returns a dict with keys `marker` (`localized` / `alternate`), `style`
    (`any` / `straight` / `italic`), `glyph_text` (the text after markers
    are stripped, e.g. `г`), and `codepoints` (list of uppercase hex
    strings). Returns None for plain tokens with no marker — those belong
    in the main character table, not in the variants table.
    """
    if not token:
        return None
    rest = token
    if rest[0] == "&":
        marker = "localized"
        rest = rest[1:]
    elif rest[0] == "+":
        marker = "alternate"
        rest = rest[1:]
    else:
        return None
    style = "any"
    for suffix, label in ((".ita", "italic"), (".str", "straight"), (".alt", "alt")):
        if rest.endswith(suffix):
            style = label
            rest = rest[: -len(suffix)]
            break
    pua_match = PUA_TOKEN.match(rest)
    if pua_match:
        codepoints = [f"{int(pua_match.group(1), 16):04X}"]
    else:
        codepoints = [f"{ord(c):04X}" for c in rest]
    return {
        "marker": marker,
        "style": style,
        "glyph_text": rest,
        "codepoints": codepoints,
    }


def collect_glyph_variants(data_root: Path, languages: list[str]) -> list[dict]:
    """Scan in-scope base JSONs and collect every token with a variant marker.

    One entry per (codepoints, case, locale, style, marker, language) tuple.
    Later aggregation merges rows that share everything except `language`.
    """
    variants: list[dict] = []
    base_dir = data_root / "library" / "cyrillic" / "base"
    for lang_name in languages:
        path = base_dir / f"{lang_name}.json"
        if not path.exists():
            continue
        with path.open(encoding="utf-8") as f:
            data = json.load(f)
        locale = data.get("local", "")
        for block in data.get("glyphs_list", []):
            block_type = block.get("type", "")
            for side in ("uppercase", "lowercase"):
                for token in (block.get(side, "") or "").split():
                    info = classify_variant_token(token)
                    if info is None:
                        continue
                    variants.append({
                        **info,
                        "token": token,
                        "case": side,
                        "locale": locale,
                        "language": lang_name,
                        "block_type": block_type,
                    })
    return variants


def aggregate_variants(variants: list[dict]) -> list[dict]:
    """Merge variant rows that share (codepoints, case, locale, style, marker).

    Different languages sometimes encode the same localized/alternate form;
    those get folded into a single row with a merged `languages` list.
    """
    groups: dict[tuple, dict] = {}
    for v in variants:
        key = (
            tuple(v["codepoints"]), v["case"], v["locale"],
            v["style"], v["marker"],
        )
        if key not in groups:
            groups[key] = {
                "codepoints": v["codepoints"],
                "case": v["case"],
                "locale": v["locale"],
                "style": v["style"],
                "marker": v["marker"],
                "glyph_text": v["glyph_text"],
                "tokens": {v["token"]},
                "languages": {v["language"]},
            }
        else:
            groups[key]["tokens"].add(v["token"])
            groups[key]["languages"].add(v["language"])
    rows = []
    for g in groups.values():
        rows.append({
            **g,
            "tokens": sorted(g["tokens"]),
            "languages": sorted(g["languages"]),
        })
    rows.sort(key=lambda r: (
        [int(cp, 16) for cp in r["codepoints"]],
        r["case"],
        r["locale"],
        r["style"],
        r["marker"],
    ))
    return rows


def render_glyph_variants_md(rows: list[dict]) -> str:
    """Render the variants table — glyphs that share a Unicode codepoint
    with a base letter but differ visually (locl forms, style alternates)."""
    by_marker = {"localized": 0, "alternate": 0}
    by_style = {"any": 0, "straight": 0, "italic": 0, "alt": 0}
    for r in rows:
        by_marker[r["marker"]] = by_marker.get(r["marker"], 0) + 1
        by_style[r["style"]] = by_style.get(r["style"], 0) + 1
    locales = sorted({r["locale"] for r in rows if r["locale"]})

    out: list[str] = []
    out.append("# Glyph variants")
    out.append("")
    out.append(
        "Glyphs that do **not** have their own Unicode codepoint: they "
        "share a codepoint with a base letter, but render as a different "
        "shape under an OpenType feature — typically `locl` (localized "
        "form, selected by the active language) or a stylistic alternate "
        "tied to upright (`.str`) or italic (`.ita`) shaping."
    )
    out.append("")
    out.append(
        "This table complements the pan-Cyrillic character tables in "
        "`characters-uppercase.md` / `characters-lowercase.md`, which are "
        "deduplicated by codepoint. The entries below are the "
        "variant-form rows that the codepoint-level view collapses."
    )
    out.append("")
    out.append(
        f"**{len(rows)}** variant forms — "
        f"{by_marker['localized']} localized (`&`), "
        f"{by_marker['alternate']} alternate (`+`). "
        f"Style breakdown: any={by_style['any']}, "
        f"straight={by_style.get('straight', 0)}, "
        f"italic={by_style.get('italic', 0)}. "
        f"Locales represented: {', '.join(locales) if locales else '—'}."
    )
    out.append("")
    out.append("## Columns")
    out.append("")
    out.append(
        "- **Codepoint** — the Unicode codepoint this variant maps to. "
        "Same as the base letter in the main table."
    )
    out.append(
        "- **Case** — uppercase / lowercase."
    )
    out.append(
        "- **Locale** — the source language's `local` field "
        "(`ru` default, `bg` Bulgarian, `sr` Serbian, …). A `&`-marked "
        "token is the localized glyph selected by that locale."
    )
    out.append(
        "- **Style** — `straight` or `italic` when the source token has "
        "a `.str` / `.ita` suffix; `any` otherwise."
    )
    out.append(
        "- **Marker** — `localized` (source token started with `&`) or "
        "`alternate` (source token started with `+`)."
    )
    out.append(
        "- **Token(s)** — verbatim source token(s) from `library/cyrillic/base/*.json`."
    )
    out.append(
        "- **Languages** — language files that declare this variant."
    )
    out.append("")
    out.append("## Variants")
    out.append("")
    out.append("| # | Codepoint | Case | Locale | Style | Marker | Token(s) | Languages |")
    out.append("| ---: | --- | --- | --- | --- | --- | --- | --- |")
    for i, r in enumerate(rows, start=1):
        out.append(
            f"| {i} | {format_unicodes(r['codepoints'])} | {r['case']} | "
            f"{r['locale']} | {r['style']} | {r['marker']} | "
            f"`{'`, `'.join(r['tokens'])}` | {', '.join(r['languages'])} |"
        )
    out.append("")
    return "\n".join(out)


def render_characters_md(side: str, entries: list[dict]) -> str:
    """Render the master table for either uppercase or lowercase characters."""
    pua_count = sum(
        1 for e in entries
        for u in e.get("unicodes", [])
        if is_pua(int(u, 16))
    )
    composed_count = sum(1 for e in entries if has_decomposition_hint(e.get("description", "")))

    out: list[str] = []
    out.append(f"# Pan-Cyrillic single characters — {side}")
    out.append("")
    out.append(f"**{len(entries)}** unique {side} characters across the 77 "
               f"languages in scope. Of these, **{pua_count}** are encoded in "
               f"the Unicode Private Use Area (E000–F8FF), and **{composed_count}** "
               f"have a composed description (`… WITH …`) that will be decomposed "
               f"into a base character plus one or more combining marks in the "
               f"next pipeline stage.")
    out.append("")
    out.append("Codepoints are shown in uppercase hex. Multi-codepoint rows use "
               "`XXXX + XXXX + …` ordering.")
    out.append("")
    out.append("| # | Sign | Codepoint | Description | PUA | Composed | Locales |")
    out.append("| ---: | :---: | --- | --- | :---: | :---: | --- |")
    for i, entry in enumerate(entries, start=1):
        sign = entry.get("sign", "")
        unicodes = entry.get("unicodes", [])
        description = entry.get("description", "")
        pua_flag = "yes" if any(is_pua(int(u, 16)) for u in unicodes) else ""
        composed_flag = "yes" if has_decomposition_hint(description) else ""
        locales = ", ".join(entry.get("locales", []))
        out.append(
            f"| {i} | {sign} | {format_unicodes(unicodes)} | "
            f"{description} | {pua_flag} | {composed_flag} | {locales} |"
        )
    out.append("")
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--data", type=Path, default=Path("../cyrillic-languages"),
        help="Path to the sibling cyrillic-languages repository "
             "(default: ../cyrillic-languages)",
    )
    parser.add_argument(
        "--out", type=Path, default=Path("."),
        help="Output directory (default: current directory)",
    )
    args = parser.parse_args(argv)

    if not args.data.exists():
        parser.error(f"--data directory does not exist: {args.data}")

    try:
        data_root = resolve_data_root(args.data)
    except FileNotFoundError as exc:
        parser.error(str(exc))

    pan = load_pan_cyrillic(data_root)
    args.out.mkdir(parents=True, exist_ok=True)

    upper = dedupe_by_codepoints(pan.get("uppercase_unicodes_list", []))
    lower = dedupe_by_codepoints(pan.get("lowercase_unicodes_list", []))

    (args.out / "characters-uppercase.md").write_text(
        render_characters_md("uppercase", upper), encoding="utf-8"
    )
    (args.out / "characters-lowercase.md").write_text(
        render_characters_md("lowercase", lower), encoding="utf-8"
    )

    variants = aggregate_variants(collect_glyph_variants(data_root, LANGUAGES_IN_SCOPE))
    (args.out / "glyph-variants.md").write_text(
        render_glyph_variants_md(variants), encoding="utf-8"
    )

    print(f"Wrote {args.out}/characters-uppercase.md ({len(upper)} entries)")
    print(f"Wrote {args.out}/characters-lowercase.md ({len(lower)} entries)")
    print(f"Wrote {args.out}/glyph-variants.md ({len(variants)} entries)")
    return 0


if __name__ == "__main__":
    sys.exit(main())
